"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Droplets, Gauge, Instagram, MapPin, Menu, Phone, ShieldCheck, Sparkles, Star, Wrench, X } from "lucide-react";

const WHATSAPP = "60123456789";
const wa = (message = "Hi NOIR Auto Detail, I'm interested in your car detailing services.") => `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`;
const hero = "https://images.unsplash.com/photo-1606577924006-27d39b132ae2?auto=format&fit=crop&w=2200&q=85";
const cars = [
  "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=80",
  "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=80"
];
const services = [
  [Droplets, "Exterior Detailing", "Hand wash, decontamination and durable paint protection."], [Sparkles, "Interior Detailing", "Deep cleaning for seats, carpets and every interior surface."], [Gauge, "Paint Correction", "Reduce swirls, oxidation and minor paint imperfections."], [ShieldCheck, "Ceramic Coating", "Long-lasting gloss with hydrophobic protection."], [Wrench, "Engine Bay Detail", "Careful cleaning and dressing beneath the bonnet."], [Star, "Headlight Restoration", "Bring clarity back to faded, oxidised headlights."]
];
const packages = [
  ["Essential Detail", [49, 59, 69], ["Exterior hand wash", "Wheel cleaning", "Interior vacuum", "Dashboard wipe", "Tyre dressing"]],
  ["Premium Detail", [129, 159, 179], ["Everything in Essential", "Interior deep clean", "Paint decontamination", "Spray wax", "Leather treatment"]],
  ["Signature Detail", [299, 349, 399], ["Everything in Premium", "Machine polish", "Paint enhancement", "Premium sealant", "Engine bay detailing", "Full interior treatment"]]
];
const faqs = [["How long does detailing take?", "Basic detailing takes around one hour, while paint correction and full treatments can take several hours."], ["Do I need an appointment?", "Appointments are recommended, especially for Premium, Signature and coating services."], ["Can polishing remove scratches?", "Light scratches and swirl marks can often be reduced. Deeper scratches may need paint repair."], ["How long does ceramic coating last?", "Longevity depends on the coating chosen, your driving conditions and regular maintenance."], ["Can I leave my car at the studio?", "Yes. You are welcome to leave your vehicle with us for longer detail sessions."]];

export default function Home() {
  const [open, setOpen] = useState(false); const [vehicle, setVehicle] = useState(0); const [compare, setCompare] = useState(52); const [faq, setFaq] = useState<number | null>(null); const [sent, setSent] = useState(false); const [activeImage, setActiveImage] = useState<string | null>(null);
  const close = () => setOpen(false);
  return <main>
    <nav className="nav"><a className="brand" href="#home" onClick={close}>NOIR <span>Auto Detail</span></a><div className={`links ${open ? "show" : ""}`}><a href="#services" onClick={close}>Services</a><a href="#packages" onClick={close}>Packages</a><a href="#gallery" onClick={close}>Gallery</a><a href="#reviews" onClick={close}>Reviews</a><a href="#contact" onClick={close}>Contact</a></div><a className="nav-cta" href="#contact">Get a Quote</a><button className="menu" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></nav>
    <section className="hero" id="home"><Image src={hero} alt="Polished premium car in a detailing studio" fill priority sizes="100vw"/><div className="shade"/><div className="hero-copy"><p className="eyebrow">Petaling Jaya Â· Premium auto care</p><h1>Your Car Deserves More Than Just a Wash.</h1><p>Professional detailing, paint correction and protection services designed to bring out the best in your car.</p><div className="actions"><a className="button" href="#contact">Get a Quote <ArrowRight size={17}/></a><a className="button ghost" href="#packages">Explore Packages</a></div><div className="rating"><span>★★★★★</span> 4.9★ · Trusted by 500+ Car Owners</div></div><p className="hero-note">Workshop notes · Est. 2021</p></section>
    <section className="stats wrap">{[["500+", "Cars Detailed"], ["4.9 / 5", "Customer Rating"], ["5+ Years", "Detailing Experience"], ["100%", "Attention to Detail"]].map(([n,l]) => <div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section>
    <section className="section wrap" id="services"><header><p className="eyebrow">The workbench</p><h2>A Better Way to Look After Your Car.</h2></header><div className="service-grid">{services.map(([Icon, title, desc]) => { const I = Icon as typeof Droplets; const serviceTitle = title as string; const serviceDescription = desc as string; return <a className="service" href="#contact" aria-label={`Ask about ${serviceTitle}`} key={serviceTitle}><I/><h3>{serviceTitle}</h3><p>{serviceDescription}</p><span><b>Explore this service</b><ArrowRight size={15}/></span></a>})}</div></section>
    <section className="section packages" id="packages"><div className="wrap"><header><p className="eyebrow">Select your starting point</p><h2>Choose Your Detail.</h2><p>Start with your vehicle. We will help with the honest next step.</p></header><div className="vehicle-toggle">{["Sedan", "SUV", "MPV"].map((v,i) => <button className={vehicle === i ? "selected" : ""} key={v} onClick={() => setVehicle(i)}>{v}</button>)}</div><div className="package-grid">{packages.map(([name, prices, items], i) => <article className={`package ${i === 1 ? "featured" : ""}`} key={name as string}>{i === 1 && <b>MOST POPULAR</b>}<p>{name}</p><div className="price"><small>Starting from</small>RM{(prices as number[])[vehicle]}</div><ul>{(items as string[]).map(x => <li key={x}><Check size={16}/>{x}</li>)}</ul><a className={i === 1 ? "button" : "button outline"} href={wa(`Hi NOIR Auto Detail, I'm interested in the ${name} package.`)} target="_blank">Enquire Now <ArrowRight size={16}/></a></article>)}</div><small className="price-note">Prices may vary depending on vehicle size and condition.</small></div></section>
    <section className="section wrap compare-section"><header><p className="eyebrow">Paint correction</p><h2>See the Difference.</h2></header><div className="comparison" role="img" aria-label="Car paint correction before and after comparison"><div className="base-layer" style={{ backgroundImage: "url(/images/paint-correction-original.jpg)" }}/><div className="before-layer" style={{ backgroundImage: "url(/images/paint-correction-muted.png)", clipPath: `inset(0 ${100 - compare}% 0 0)` }}/><input aria-label="Before and after comparison" type="range" min="5" max="95" value={compare} onInput={e => setCompare(Number(e.currentTarget.value))}/><i style={{left: `${compare}%`}}/><span className="before-label">BEFORE</span><span className="after-label">AFTER</span></div><p className="caption">Paint Correction — before / after</p></section>
    <section className="coating"><Image src="https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1900&q=85" alt="Glossy car paint detail" fill sizes="100vw"/><div className="shade"/><div className="wrap coating-content"><p className="eyebrow">Ceramic coating</p><h2>Protection That Goes Beyond Shine.</h2><p>Professional-grade coating that makes every drive easier to maintain.</p><div className="benefits">{["Hydrophobic protection", "UV resistance", "Enhanced gloss", "Easier maintenance", "Chemical resistance"].map(x => <span key={x}><Check size={16}/>{x}</span>)}</div><p className="coating-price">Ceramic Coating from <strong>RM599</strong></p><a className="button" href={wa("Hi NOIR Auto Detail, I'd like to ask about ceramic coating.")} target="_blank">Ask About Ceramic Coating</a></div></section>
    <section className="section wrap" id="gallery"><header><p className="eyebrow">From the studio floor</p><h2>This Week at NOIR.</h2></header><div className="gallery">{cars.map((src,i) => <button onClick={() => setActiveImage(src)} key={src}><Image src={src} alt={`NOIR Auto Detail recent vehicle ${i + 1}`} fill sizes="(max-width: 700px) 50vw, 33vw"/><span>Open job card <ArrowRight size={15}/></span></button>)}</div><p className="disclaimer">Vehicle makes shown are for visual portfolio purposes only and do not imply endorsement.</p></section>
    <section className="section wrap why"><header><p className="eyebrow">Built around care</p><h2>Detailing Done Properly.</h2></header><div>{[["01", "Professional Care", "Every vehicle is treated carefully, with the same focus from first rinse to final inspection."], ["02", "Premium Products", "Professional detailing products and equipment chosen to protect your surfaces."], ["03", "Transparent Pricing", "Clear starting prices and a straightforward recommendation for your car."], ["04", "Attention to Detail", "We focus on the areas normal car washes often overlook."]].map(([n,t,d]) => <article key={n}><em>{n}</em><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="section reviews" id="reviews"><div className="wrap"><header><p className="eyebrow">From the driver seat</p><h2>What Car Owners Say.</h2></header><div className="review-grid">{[["Sent my Civic for their Premium Detail. Interior came out really clean and the paint feels much smoother now. Overall very satisfied.", "Jason â€” Honda Civic"], ["They actually took their time with the car instead of rushing through it. Good workmanship and friendly service.", "Amir â€” BMW 320i"], ["My family SUV had been through a lot. The difference in the interior after collection was honestly impressive.", "Nadia â€” Mazda CX-5"]].map(([q,n]) => <figure key={n}><Star/><blockquote>â€œ{q}â€</blockquote><figcaption>{n}</figcaption></figure>)}</div></div></section>
    <section className="enquiry" id="contact"><div className="wrap enquiry-grid"><div><p className="eyebrow">Simple enquiry</p><h2>Tell Us What You Notice.</h2><p>Tell us a little about your vehicle. Weâ€™ll point you in the right direction.</p><a href={wa()} target="_blank" className="text-link">Or chat with us on WhatsApp <ArrowRight size={16}/></a></div><form onSubmit={e => {e.preventDefault(); setSent(true)}}>{sent ? <div className="success"><Check size={27}/><h3>Thanks! We&apos;ll contact you shortly.</h3><p>Your request has been noted for this prototype.</p></div> : <><input required placeholder="Your name"/><input required placeholder="Phone number" type="tel"/><input required placeholder="Car model"/><select defaultValue=""><option value="" disabled>Interested package</option><option>Essential Detail</option><option>Premium Detail</option><option>Signature Detail</option><option>Ceramic Coating</option></select><button className="button" type="submit">Request a Quote <ArrowRight size={17}/></button></>}</form></div></section>
    <section className="section wrap visit"><header><p className="eyebrow">Find us</p><h2>Visit Our Studio.</h2></header><div className="visit-grid"><div className="map"><MapPin size={28}/><strong>NOIR AUTO DETAIL</strong><span>Petaling Jaya, Selangor</span></div><div className="contact-list"><p><strong>NOIR Auto Detail</strong><br/>Petaling Jaya, Selangor, Malaysia</p><p><strong>Monday â€” Saturday</strong><br/>9:00 AM â€” 7:00 PM<br/><br/><strong>Sunday</strong><br/>By Appointment</p><a href="tel:+60123456789"><Phone size={16}/> +60 12-345 6789</a><a href="https://instagram.com" target="_blank"><Instagram size={16}/> @noir.autodetail</a><a className="text-link" href="https://maps.google.com/?q=Petaling+Jaya" target="_blank">Get Directions <ArrowRight size={16}/></a></div></div></section>
    <section className="section wrap faq"><header><p className="eyebrow">Good to know</p><h2>Questions, Answered.</h2></header>{faqs.map(([q,a],i) => <article key={q}><button onClick={() => setFaq(faq === i ? null : i)}>{q}<ChevronDown className={faq === i ? "rotate" : ""}/></button>{faq === i && <p>{a}</p>}</article>)}</section>
    <section className="final"><div className="wrap"><p className="eyebrow">A note from the studio</p><h2>Give Your Car the Finish It Deserves.</h2><p>No hard sell. Just a clear conversation about what will make your car feel right again.</p><div className="actions"><a className="button" href="#contact">Get a Quote <ArrowRight size={17}/></a><a className="button ghost" href={wa()} target="_blank">WhatsApp Us</a></div></div></section>
    <footer className="wrap"><div><a className="brand" href="#home">NOIR <span>Auto Detail</span></a><p>Workshop notes · Est. 2021</p></div><div className="footer-links"><a href="#services">Services</a><a href="#packages">Packages</a><a href="#gallery">Gallery</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></div><small>Â© 2026 NOIR Auto Detail. All rights reserved.<br/>Demo website created for portfolio purposes.</small></footer>
    <a className="whatsapp" href={wa()} target="_blank" aria-label="Chat on WhatsApp"><span>Chat on WhatsApp</span><Phone size={21}/></a>
    {activeImage && <div className="modal" role="dialog" aria-modal="true" onClick={() => setActiveImage(null)}><button aria-label="Close gallery image"><X/></button><Image src={activeImage} alt="Expanded recent vehicle detail" fill sizes="90vw"/></div>}
  </main>;
}
